name: kaptureone
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.11.0
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.8.4
  google_sign_in:
  flutter_facebook_login: ^2.0.0
  cloud_firestore: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
  uses-material-design: true

  assets:
  - assets/images/google.svg
  - assets/images/facebook.svg
  - assets/images/bg.png
  - assets/images/location.png
  - assets/images/location_pin.png
  - assets/images/logo.png
  - assets/images/deals.png
  - assets/images/icon1.png
  - assets/images/icon2.png
  - assets/images/icon3.png
  - assets/images/icon4.png
  - assets/images/icon5.png
  - assets/images/icon6.png
  - assets/images/icon7.png
  - assets/images/icon8.png
  - assets/images/icon9.png
  - assets/images/login_vector.png
  - assets/images/code_vector.png
  - assets/images/signup_vector.png
