name: kaptureone
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.11.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
  - assets/images/google.svg
  - assets/images/facebook.svg
  - assets/images/bg.png
  - assets/images/location.png
  - assets/images/location_pin.png
  - assets/images/logo.png
  - assets/images/dropdown.png